import {test,expect} from '@playwright/test';
test('services, project details and dialog focus work',async({page})=>{
 await page.goto('/');await expect(page.locator('.service-card')).toHaveCount(6);
 await page.getByRole('button',{name:'Learn More about AI Automation'}).click();
 await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('dialog').getByRole('heading',{name:'AI Automation'})).toBeVisible();
 await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();await expect(page.getByRole('button',{name:'Learn More about AI Automation'})).toBeFocused();
 await page.getByRole('button',{name:'View Brand Repositioning project'}).click();await expect(page.getByRole('dialog').getByText('+2.6x Revenue')).toBeVisible();
});
test('FAQ toggles independently and carousel wraps with buttons and keyboard',async({page})=>{
 await page.goto('/');const faq=page.getByRole('button',{name:'2. How do you work with clients?'});await faq.click();await expect(faq).toHaveAttribute('aria-expanded','true');await expect(page.locator('#faq-button-0')).toHaveAttribute('aria-expanded','false');await faq.click();await expect(faq).toHaveAttribute('aria-expanded','false');
 await page.getByRole('button',{name:'Next testimonial'}).click();await expect(page.getByText('Showing testimonial 2 of 3: Michael Chen')).toBeAttached();await page.getByRole('region',{name:'Client testimonials'}).focus();await page.keyboard.press('ArrowRight');await expect(page.getByText('Showing testimonial 3 of 3: Emily Carter')).toBeAttached();await page.keyboard.press('ArrowRight');await expect(page.getByText('Showing testimonial 1 of 3: Sarah Johnson')).toBeAttached();
});
test('contact form saves an honest local draft and downloads it',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Get Started',exact:true}).first().click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Your name').fill('Test Person');await dialog.getByLabel('Email address').fill('test@example.com');await dialog.getByLabel('About your project').fill('Build a responsive website.');await dialog.getByRole('button',{name:'Save project brief'}).click();await expect(dialog.getByText('It has not been sent to Nexora.',{exact:false})).toBeVisible();const download=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download your brief'}).click();expect((await download).suggestedFilename()).toBe('nexora-project-brief.txt');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('nexora-enquiry')||'{}').name)).toBe('Test Person');
});
test('mobile menu scroll lock, anchors, escape and swipe work',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByRole('button',{name:'Open navigation'}).click();await expect(page.getByRole('navigation',{name:'Mobile navigation'})).toBeVisible();expect(await page.evaluate(()=>document.body.style.overflow)).toBe('hidden');await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('link',{name:'Services'}).click();await expect(page.getByRole('navigation',{name:'Mobile navigation'})).not.toBeVisible();expect(await page.evaluate(()=>document.body.style.overflow)).not.toBe('hidden');await expect(page).toHaveURL(/#services$/);await page.getByRole('button',{name:'Open navigation'}).click();await page.keyboard.press('Escape');await expect(page.getByRole('navigation',{name:'Mobile navigation'})).not.toBeVisible();
 const carousel=page.locator('.testimonial-window');await carousel.dispatchEvent('touchstart',{touches:[{identifier:0,clientX:300}]});await carousel.dispatchEvent('touchend',{changedTouches:[{identifier:0,clientX:150}]});await expect(page.getByText('Showing testimonial 2 of 3: Michael Chen')).toBeAttached();
});
test('email preference, journal, sitemap and local privacy removal work',async({page})=>{
 await page.goto('/');await page.getByLabel('Your email address',{exact:true}).fill('reader@example.com');await page.getByRole('button',{name:'Save email preference'}).click();await expect(page.getByText('Email saved on this device. No subscription has been sent.')).toBeVisible();await page.locator('.desktop-nav').getByRole('button',{name:'Blog'}).click();await expect(page.getByRole('dialog').locator('article')).toHaveCount(3);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Sitemap',exact:true}).click();await page.getByRole('dialog').getByRole('link',{name:'FAQ'}).click();await expect(page).toHaveURL(/#faq$/);await page.getByRole('button',{name:'Privacy Policy',exact:true}).click();await page.getByRole('button',{name:'Clear saved local data'}).click();expect(await page.evaluate(()=>localStorage.getItem('nexora-newsletter'))).toBeNull();
});
for(const width of [1440,1280,1024,768,430,390,375,320])test(`responsive layout fits at ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});await page.goto('/');expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);await expect(page.locator('.service-card')).toHaveCount(6);expect(await page.locator('.services-grid').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length)).toBe(width>=1024?3:width>=768?2:1)});

