import { useEffect, useRef, useState, type ReactNode, type FormEvent } from 'react';
import { ArrowRight, ArrowLeft, ArrowDown, Play, Menu, X, Plus, Minus, CalendarDays, MessageCircle, ShoppingBag, Check } from 'lucide-react';
import gsap from 'gsap';
import TechnologyBar from './TechnologyBar';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { services, projects, steps, testimonials, faq, navigation } from './data';
gsap.registerPlugin(ScrollTrigger);
function InstagramIcon({size=17}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".8" fill="currentColor"/></svg>}
function LinkedinIcon({size=17}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M4 8h4v13H4zm2-6a2 2 0 1 1 0 4 2 2 0 0 1 0-4m5 6h4v2c1-2 6-3 6 3v8h-4v-7c0-3-2-3-2 0v7h-4z"/></svg>}
function YoutubeIcon({size=17}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><rect x="2" y="5" width="20" height="14" rx="4"/><path d="m10 9 5 3-5 3z" fill="currentColor" stroke="none"/></svg>}
type ModalContent = { title:string; eyebrow?:string; body:ReactNode } | null;
const img = (name:string) => `/assets/${name}.webp`;
function Logo(){return <a href="#home" className="logo" aria-label="Nexora home"><span className="logo-mark" aria-hidden="true"/>Nexora</a>}
function Button({children,href,onClick,primary=false,className=''}:{children:ReactNode;href?:string;onClick?:()=>void;primary?:boolean;className?:string}){ const content=<>{children}<ArrowRight size={15}/></>;return href?<a className={`button ${primary?'primary':''} ${className}`} href={href}>{content}</a>:<button className={`button ${primary?'primary':''} ${className}`} onClick={onClick}>{content}</button> }
function Eyebrow({children}:{children:ReactNode}){return <p className="eyebrow">{children}</p>}
function ContactForm({subject='A new project'}:{subject?:string}){
 const [saved,setSaved]=useState(false);const [error,setError]=useState('');
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));try{localStorage.setItem('nexora-enquiry',JSON.stringify({...data,createdAt:new Date().toISOString()}));setSaved(true)}catch{setError('Your browser could not save this draft. You can still copy your details below.')}}
 return saved?<div className="form-success" role="status"><span className="icon-badge teal"><Check/></span><h3>Your project brief is saved.</h3><p>This is a local draft on this device. It has not been sent to Nexora.</p><button className="button" onClick={()=>{const raw=localStorage.getItem('nexora-enquiry')||'{}';const data=JSON.parse(raw);const file=new Blob([`Nexora project enquiry\n\nName: ${data.name}\nEmail: ${data.email}\nService: ${data.service}\n\n${data.message}`],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(file);a.download='nexora-project-brief.txt';a.click();URL.revokeObjectURL(a.href)}}>Download your brief <ArrowDown size={15}/></button></div>:<form className="contact-form" onSubmit={submit}><p>Tell us a little about what you’re building.</p><div className="form-row"><label>Your name<input name="name" required autoComplete="name" placeholder="Alex Morgan" maxLength={100}/></label><label>Email address<input name="email" type="email" required autoComplete="email" placeholder="you@company.com" maxLength={254}/></label></div><label>What can we help with?<select name="service" defaultValue={services.some(s=>s.name===subject)?subject:'A new project'}><option>A new project</option>{services.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label>About your project<textarea name="message" required rows={4} maxLength={3000} placeholder="Your goals, ideas and a little about your business…"/></label><p className="form-note">No enquiry service is connected yet. Save a private draft on this device and download it to share.</p>{error&&<p role="alert">{error}</p>}<button className="button primary" type="submit">Save project brief <ArrowRight size={15}/></button></form>
}
function Modal({content,close}:{content:ModalContent;close:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(content){dialog.current?.showModal();const prior=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{dialog.current?.close();document.body.style.overflow=prior}}},[content]);
 return <dialog ref={dialog} className="modal" onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close()}}><div className="modal-inner"><button className="circle-button modal-close" aria-label="Close dialog" onClick={close}><X size={20}/></button>{content&&<>{content.eyebrow&&<Eyebrow>{content.eyebrow}</Eyebrow>}<h2>{content.title}</h2>{content.body}</>}</div></dialog>
}
function App(){
 const [modal,setModal]=useState<ModalContent>(null);const [menuOpen,setMenuOpen]=useState(false);const [active,setActive]=useState('Home');const [scrolled,setScrolled]=useState(false);const [slide,setSlide]=useState(0);const [visibleSlides,setVisibleSlides]=useState(3);const [faqOpen,setFaqOpen]=useState<number|null>(0);const [newsletter,setNewsletter]=useState('');const [newsletterStatus,setNewsletterStatus]=useState('');const root=useRef<HTMLDivElement>(null);const touch=useRef<number|null>(null);
 const contact=(subject?:string)=>setModal({eyebrow:'LET’S BUILD SOMETHING GREAT',title:'Your next chapter starts here.',body:<ContactForm key={subject||'contact'} subject={subject}/>});
 const serviceModal=(index:number)=>{const s=services[index];setModal({eyebrow:'OUR SERVICES',title:s.name,body:<><p>{s.detail}</p><ul className="detail-list">{s.features.map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul><Button primary onClick={()=>contact(s.name)}>Let’s talk about your project</Button></>})};
 const projectModal=(index:number)=>{const p=projects[index];setModal({eyebrow:p.category,title:p.name,body:<><img className="project-detail-image" src={img(p.image)} alt={`${p.name} campaign concept`}/><p className="project-result">{p.result}</p><p>{p.description}</p><h3>The approach</h3><p>{p.approach}</p><p className="form-note">Illustrative portfolio content reproduced from the supplied design reference.</p><Button onClick={()=>contact(p.category)}>Build something like this</Button></>})};
 const blog=()=>setModal({eyebrow:'THE NEXORA JOURNAL',title:'Ideas for what comes next.',body:<div className="journal">{[['A website that works as hard as you do','Start with the actions your customers need to take. A clear page hierarchy, fast load times and an easy enquiry flow make a better foundation than adding more features. Review the journey on a phone first, then remove anything that stands between a visitor and their goal.'],['Start small with AI automation','Choose one repetitive workflow with a measurable outcome. Map the inputs, define an approval step and keep a human handoff. A useful first automation might organize enquiries or draft follow-ups — with your team reviewing the result before anything is sent.'],['Connect your tools, connect your growth','Customer data often lives across forms, spreadsheets and inboxes. Bring the essential information into one CRM, agree on ownership and create a simple follow-up process. Clear workflows help your team spend less time searching and more time serving customers.']].map(([title,text])=><article key={title}><Eyebrow>STRATEGY · 3 MIN READ</Eyebrow><h3>{title}</h3><p>{text}</p></article>)}</div>});
 const policy=(kind:string)=>setModal({eyebrow:'NEXORA',title:kind,body:kind==='Privacy Policy'?<><p>This preview does not send form data to a server. Project briefs and email preferences are stored only in your browser when you explicitly save them.</p><p>You can remove saved data at any time using the control below. Final business privacy terms must be added before launch.</p><Button onClick={()=>{localStorage.removeItem('nexora-enquiry');localStorage.removeItem('nexora-newsletter');setNewsletterStatus('Local data cleared.');setModal(null)}}>Clear saved local data</Button></>:<><p>This website is a design implementation preview. Its portfolio metrics and testimonials follow the supplied reference and are illustrative until verified by the business.</p><p>No purchases, bookings or service agreements are made through this preview. Final business terms must be added before public launch.</p></>});
 useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>30);onScroll();window.addEventListener('scroll',onScroll,{passive:true});const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){const names:Record<string,string>={home:'Home',services:'Services',process:'Process',work:'Work',about:'About'};setActive(names[e.target.id]||'Home')}})},{rootMargin:'-15% 0px -65% 0px'});document.querySelectorAll('main section[id]').forEach(el=>observer.observe(el));return()=>{window.removeEventListener('scroll',onScroll);observer.disconnect()}},[]);
 useEffect(()=>{const update=()=>setVisibleSlides(window.innerWidth<768?1:window.innerWidth<=950?2:3);update();window.addEventListener('resize',update);return()=>window.removeEventListener('resize',update)},[]);
 useEffect(()=>{if(!menuOpen)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const links=[...document.querySelectorAll<HTMLElement>('#mobile-nav a, #mobile-nav button')];links[0]?.focus();const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenuOpen(false);if(e.key==='Tab'){const toggle=document.querySelector<HTMLElement>('.menu-toggle');const controls=[toggle,...links].filter((el):el is HTMLElement=>el!==null);const index=controls.indexOf(document.activeElement as HTMLElement);if(e.shiftKey&&index===0){e.preventDefault();controls.at(-1)?.focus()}else if(!e.shiftKey&&index===controls.length-1){e.preventDefault();controls[0]?.focus()}}};document.addEventListener('keydown',escape);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',escape);document.querySelector<HTMLElement>('.menu-toggle')?.focus()}},[menuOpen]);
 useEffect(()=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{const ctx=gsap.context(()=>{const entrance=gsap.timeline();entrance.from('.hero-copy .eyebrow',{y:12,opacity:0,duration:.5},0).from('.hero-title-line:first-child .hero-letter',{yPercent:105,rotationX:-65,opacity:0,duration:.85,stagger:.035,ease:'power3.out'},.15).from('.hero-title-line.gradient .hero-letter',{yPercent:105,rotationX:-65,opacity:0,duration:.95,stagger:.045,ease:'power3.out'},.5).from('.hero-description, .hero-copy .button-row',{y:15,opacity:0,duration:.65,stagger:.12},.95).fromTo('.hero-title-line.gradient .hero-letter',{backgroundPosition:'0% 50%'},{backgroundPosition:(i:number)=>`${i*12.5}% 50%`,duration:2.3,ease:'sine.inOut'},.7);gsap.from('.hero-visual',{y:25,opacity:0,duration:1.25,delay:.2,ease:'power2.out'});gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.from(el,{y:22,opacity:0,duration:.7,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 94%',once:true}}));gsap.to('.hero-visual',{y:-35,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});gsap.to('.hero-environment',{y:55,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});gsap.from('.timeline-progress',{scaleX:0,transformOrigin:'left',ease:'none',scrollTrigger:{trigger:'.timeline',start:'top 85%',end:'bottom 55%',scrub:1}});gsap.utils.toArray<HTMLElement>('.parallax-object').forEach(el=>gsap.fromTo(el,{y:20},{y:-15,ease:'none',scrollTrigger:{trigger:el,start:'top bottom',end:'bottom top',scrub:1}}));gsap.utils.toArray<HTMLElement>('[data-count]').forEach(el=>{const target=Number(el.dataset.count);const value={n:0};gsap.to(value,{n:target,duration:1.4,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 95%',once:true},onUpdate:()=>{el.textContent=value.n.toFixed(target===4.9?1:0)}})})},root);return()=>ctx.revert()});return()=>mm.revert()},[]);
 const changeSlide=(direction:number)=>setSlide(v=>(v+direction+testimonials.length)%testimonials.length);
 function saveNewsletter(e:FormEvent){e.preventDefault();try{localStorage.setItem('nexora-newsletter',newsletter);setNewsletterStatus('Email saved on this device. No subscription has been sent.');setNewsletter('')}catch{setNewsletterStatus('Unable to save. Please check your browser storage settings.')}}
 return <div ref={root}>
 <a className="skip-link" href="#services">Skip to content</a>
 <header className={`header ${scrolled?'scrolled':''}`}><div className="container header-inner"><Logo/><nav aria-label="Main navigation" className="desktop-nav">{navigation.map(([name,href])=>href==='blog'?<button key={name} onClick={blog}>{name}</button>:<a key={name} href={href} className={active===name?'active':''} aria-current={active===name?'location':undefined}>{name}</a>)}</nav><Button className="header-cta" onClick={()=>contact()}>Let’s Talk</Button><button className="menu-toggle circle-button" aria-label={menuOpen?'Close navigation':'Open navigation'} aria-expanded={menuOpen} aria-controls="mobile-nav" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></div></header>
 {menuOpen&&<nav id="mobile-nav" className="mobile-nav" aria-label="Mobile navigation">{navigation.map(([name,href])=>href==='blog'?<button key={name} onClick={()=>{setMenuOpen(false);blog()}}>{name}</button>:<a key={name} href={href} onClick={()=>setMenuOpen(false)}>{name}<ArrowRight size={20}/></a>)}<Button primary onClick={()=>{setMenuOpen(false);contact()}}>Let’s Talk</Button></nav>}
 <main inert={menuOpen}>
 <section className="hero" id="home"><img className="hero-environment" src={img('hero-environment')} width="1536" height="864" alt="" fetchPriority="high"/><div className="hero-shade"/><div className="container hero-main"><div className="hero-copy"><Eyebrow><span className="eyebrow-dots">···</span> STRATEGY · CREATIVE · TECHNOLOGY</Eyebrow><h1 aria-label="Build Brands That Grow"><span className="hero-title-line" aria-hidden="true">{[... 'Build Brands'].map((letter,i)=><span className="hero-letter" key={i}>{letter===' '?'\u00a0':letter}</span>)}</span><span className="hero-title-line gradient" aria-hidden="true">{[... 'That Grow'].map((letter,i)=><span className="hero-letter" key={i} style={{backgroundPosition:`${i*12.5}% 50%`}}>{letter===' '?'\u00a0':letter}</span>)}</span></h1><p className="hero-description">We build digital platforms, automation systems and growth infrastructure that help businesses operate smarter, engage customers and scale.</p><div className="button-row"><Button primary onClick={()=>contact()}>Get Started</Button><button className="button showreel" onClick={()=>setModal({eyebrow:'SELECTED WORK',title:'A little vision. A lot of possibility.',body:<><p>Explore four worlds of strategy, creativity and growth.</p><div className="showreel-grid">{projects.map((p,i)=><button key={p.name} onClick={()=>projectModal(i)}><img src={img(p.image)} alt={p.name}/><span>{p.name}<ArrowRight size={15}/></span></button>)}</div></>})}><Play size={14}/>Watch Showreel</button></div></div><div className="hero-visual" onPointerMove={e=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches||e.pointerType!=='mouse')return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--tilt-x',`${((e.clientY-r.top)/r.height-.5)*-3}deg`);e.currentTarget.style.setProperty('--tilt-y',`${((e.clientX-r.left)/r.width-.5)*4}deg`)}} onPointerLeave={e=>{e.currentTarget.style.setProperty('--tilt-x','0deg');e.currentTarget.style.setProperty('--tilt-y','0deg')}}><div className="hero-device"><img src={img('hero-device')} width="1536" height="1024" alt="Black glass laptop illuminated with violet and magenta light" fetchPriority="high"/><div className="device-copy"><span>Ideas</span><span>Strategy</span><span>Systems</span><span>Growth</span></div><div className="device-note"><span className="energy-orbit"/>Turn<br/>Your Vision<br/>Into Reality</div></div></div></div><div className="container stats-area"><div className="stats">{[[250,'+','Brands Scaled'],[4.9,'/5','Client Rating'],[3,'x','Average Growth'],[100,'%','Client Focused']].map(([value,suffix,label])=><div className="stat" key={label}><span className="stat-dot"/><strong><span data-count={value}>{value}</span>{suffix}</strong><span>{label}</span></div>)}</div><a href="#services" className="scroll-explore"><span className="scroll-circle"><ArrowDown size={18}/><i/></span><span>SCROLL<br/>TO EXPLORE</span></a></div></section>
 <TechnologyBar/>
 <section className="container section services-section" id="services"><div className="section-heading reveal"><div><Eyebrow>SERVICES</Eyebrow><h2>Everything you need<br/>to grow — under one roof.</h2></div><div className="heading-aside"><p>From powerful websites to intelligent systems, we help you attract, engage and grow your audience.</p><Button href="#service-grid">Explore All Services</Button></div></div><div className="services-grid" id="service-grid">{services.map((s,i)=><article className={`service-card reveal ${s.color}`} key={s.name}><span className={`icon-badge ${s.color}`}><s.icon size={23}/></span><h3>{s.name}</h3><p>{s.description}</p><button className="text-link" onClick={()=>serviceModal(i)}>Learn More <ArrowRight size={15}/><span className="sr-only"> about {s.name}</span></button></article>)}</div></section>
 <section className="container section process-section" id="process"><div className="process-intro"><div className="reveal"><Eyebrow>THE PROCESS</Eyebrow><h2>From Strategy<br/>to Measurable Growth</h2><p>A proven process designed to turn your goals into real business outcomes.</p><Button primary href="#timeline">Our Process</Button></div><div className="process-art parallax-object"><img src={img('process-sphere')} width="1024" height="1024" loading="lazy" alt="Translucent black glass sphere with flowing coral and violet light"/><span className="sphere-copy">IDEAS<br/>STRATEGY<br/>EXECUTION<br/>GROWTH<i/></span></div></div><div className="timeline" id="timeline"><div className="timeline-line"><span className="timeline-progress"/></div>{steps.map((s,i)=><button className={`process-step reveal step-${i}`} key={s.name} onClick={()=>setModal({eyebrow:`OUR PROCESS · 0${i+1}`,title:s.name,body:<><p>{s.detail}</p><Button primary onClick={()=>contact()}>Start your journey</Button></>})}><span className="step-node"><s.icon size={22}/></span><span className="step-arrow" aria-hidden="true">›</span><h3>0{i+1} {s.name}</h3><p>{s.text}</p></button>)}</div></section>
 <section className="container section work-section" id="work"><div className="section-heading reveal"><div><Eyebrow>OUR WORK</Eyebrow><h2>Real Brands.<br/>Real Results.</h2></div><div className="heading-aside"><p>We partner with forward-thinking businesses to create impactful digital experiences and measurable growth.</p><Button onClick={()=>setModal({eyebrow:'SELECTED PROJECTS',title:'Good ideas. Great execution.',body:<div className="all-work">{projects.map((p,i)=><button key={p.name} onClick={()=>projectModal(i)}><img src={img(p.image)} alt={p.name}/><span><strong>{p.name}</strong><small>{p.category}</small></span><ArrowRight size={20}/></button>)}</div>})}>View All Work</Button></div></div><div className="project-grid">{projects.map((p,i)=><button className="project-card reveal" key={p.name} onClick={()=>projectModal(i)} aria-label={`View ${p.name} project`}><img src={img(p.image)} width="768" height="1024" alt={`${p.name} campaign visual`} loading="lazy"/><div className="project-caption"><div><h3>{p.name}</h3><p>{p.result}</p></div><span className="circle-button"><ArrowRight size={17}/></span></div></button>)}</div></section>
 <section className="container section testimonials-section" id="about"><div className="section-heading reveal"><div><Eyebrow>TESTIMONIALS</Eyebrow><h2>What our<br/>clients say</h2></div><div className="heading-aside testimonial-aside"><p>Trusted by founders, marketers, and growing brands around the world.</p><div className="carousel-controls"><button className="circle-button" aria-label="Previous testimonial" onClick={()=>changeSlide(-1)}><ArrowLeft size={19}/></button><button className="circle-button" aria-label="Next testimonial" onClick={()=>changeSlide(1)}><ArrowRight size={19}/></button></div></div></div><div className="testimonial-window reveal" role="region" aria-roledescription="carousel" aria-label="Client testimonials" tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();changeSlide(1)}if(e.key==='ArrowLeft'){e.preventDefault();changeSlide(-1)}}} onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{if(touch.current!==null){const delta=e.changedTouches[0].clientX-touch.current;if(Math.abs(delta)>40)changeSlide(delta<0?1:-1);touch.current=null}}}><div className="testimonial-track" style={{transform:`translateX(calc(-${slide} * (100% / var(--visible) + var(--card-gap) / var(--visible))))`}}>{[...testimonials,...testimonials].map((t,i)=><article className="testimonial-card" key={`${t.name}-${i}`} aria-hidden={i<slide||i>=slide+visibleSlides}><blockquote>“{t.quote}”</blockquote><div className="testimonial-person"><span className={`avatar ${t.tone}`} aria-hidden="true">{t.initials}</span><div><h3>{t.name}</h3><p>{t.role}</p></div></div></article>)}</div></div><p className="sr-only" aria-live="polite">Showing testimonial {slide+1} of {testimonials.length}: {testimonials[slide].name}</p><div className="carousel-dots" aria-label="Choose testimonial">{testimonials.map((t,i)=><button key={t.name} className={slide===i?'selected':''} aria-label={`Show ${t.name}'s testimonial`} aria-pressed={slide===i} onClick={()=>setSlide(i)}/>)}</div></section>
 <section className="cta-section" id="contact"><div className="cta-landscape"/><div className="container cta-inner"><div className="cta-copy reveal"><h2>Ready to grow<br/>your brand?</h2><p>Let’s discuss how we can help you achieve your goals with strategy, creativity, and technology that moves you forward.</p><div className="button-row"><Button primary onClick={()=>contact()}>Get Started</Button><button className="button" onClick={()=>contact('Book a call')}><CalendarDays size={15}/>Book a Call</button></div></div><div className="cta-visual parallax-object"><img src={img('cta-device')} width="1536" height="864" loading="lazy" alt="Floating black glass display with a magenta signal waveform above volcanic rocks"/><span className="cta-screen-copy">BIGGER<br/>BRANDS<br/>BRIGHTER<br/>FUTURES</span><button className="circle-button cta-device-arrow" aria-label="Start your project" onClick={()=>contact()}><ArrowRight size={20}/></button></div></div></section>
 <section className="container faq-section" id="faq"><div className="faq-left"><div className="reveal"><Eyebrow>FAQ</Eyebrow><h2>Frequently Asked<br/>Questions</h2></div><div className="faq-orb parallax-object"><img src={img('faq-sphere')} width="1024" height="1024" loading="lazy" alt=""/><div className="chat-card"><span className="chat-icon"><MessageCircle size={17}/></span><h3>Have a question?</h3><p>We’re just a message away.</p><Button onClick={()=>contact()}>Chat with Us</Button></div></div></div><div className="faq-right reveal"><div className="faq-aside"><p>Still have questions? We’re here to help.</p><Button onClick={()=>contact()}>Contact Us</Button></div><div className="accordion">{faq.map(([question,answer],i)=><div className={`accordion-item ${faqOpen===i?'open':''}`} key={question}><h3><button aria-expanded={faqOpen===i} aria-controls={`faq-panel-${i}`} id={`faq-button-${i}`} onClick={()=>setFaqOpen(faqOpen===i?null:i)}>{i+1}. {question}{faqOpen===i?<Minus size={18}/>:<Plus size={18}/>}</button></h3><div id={`faq-panel-${i}`} role="region" aria-labelledby={`faq-button-${i}`} hidden={faqOpen!==i}><p>{answer}</p></div></div>)}</div></div></section>
 </main>
 <footer className="footer" inert={menuOpen}><div className="container footer-grid"><div className="footer-brand"><Logo/><p>Strategy. Systems. Growth.<br/>All in one place.</p></div><div className="footer-links"><h3>Quick Links</h3>{[['Home','#home'],['Services','#services'],['Work','#work'],['About','#about'],['Blog','blog'],['Contact','contact']].map(([name,href])=>href==='blog'||href==='contact'?<button key={name} onClick={href==='blog'?blog:()=>contact()}>{name}</button>:<a key={name} href={href}>{name}</a>)}</div><div className="footer-links footer-services"><h3>Services</h3>{services.map((s,i)=><button key={s.name} onClick={()=>serviceModal(i)}>{s.name}</button>)}</div><div className="footer-follow"><h3>Follow Us</h3><div className="social-links">{[[X,'X'],[LinkedinIcon,'LinkedIn'],[InstagramIcon,'Instagram'],[YoutubeIcon,'YouTube']].map(([Icon,name])=>{const I=Icon as typeof X;return <button key={String(name)} aria-label={`Connect on ${name}`} onClick={()=>setModal({eyebrow:'STAY CONNECTED',title:`Find us on ${name}.`,body:<><p>Our verified social profile will be added before launch. In the meantime, tell us how you’d like to connect.</p><Button onClick={()=>contact()}>Get in touch</Button></>})}><I size={17}/></button>})}</div><form className="newsletter-form" onSubmit={saveNewsletter}><label className="sr-only" htmlFor="newsletter-email">Your email address</label><input id="newsletter-email" type="email" placeholder="Enter your email" required value={newsletter} onChange={e=>setNewsletter(e.target.value)} maxLength={254}/><button aria-label="Save email preference" type="submit"><ArrowRight size={18}/></button></form><p className="newsletter-status" role="status">{newsletterStatus}</p></div></div><div className="container footer-bottom"><p>© {new Date().getFullYear()} Nexora. All rights reserved.</p><div><button onClick={()=>policy('Privacy Policy')}>Privacy Policy</button><button onClick={()=>policy('Terms of Service')}>Terms of Service</button><button onClick={()=>setModal({eyebrow:'EXPLORE NEXORA',title:'Sitemap',body:<div className="sitemap">{[...navigation.filter(([,href])=>href!=='blog'),['FAQ','#faq'],['Contact','#contact']].map(([name,href])=><a key={name} href={href} onClick={()=>setModal(null)}>{name}<ArrowRight size={16}/></a>)}</div>})}>Sitemap</button></div><p>Made with <span className="heart">♡</span> for bigger brands.</p></div></footer><Modal content={modal} close={()=>setModal(null)}/>
 </div>
}
export default App;



