import { Globe2, Workflow, Sparkles, MessagesSquare, MapPin, ShoppingBag, Search, Route, Rocket, ChartNoAxesCombined } from 'lucide-react';
export const services = [
  { name: 'Website Development', icon: Globe2, color: 'violet', description: 'Fast, beautifully crafted websites that turn visitors into customers.', detail: 'From a focused landing page to a complete business platform, we design and develop responsive websites around your customers. Every build includes accessible interfaces, search-ready foundations, performance optimization and a clear handover.', features: ['Responsive design & development', 'Performance & SEO foundations', 'Content management & integrations'] },
  { name: 'Customize CRM', icon: Workflow, color: 'coral', description: 'Connected workflows and customer relationships, built around your business.', detail: 'Your CRM should fit the way you work. We map your sales and operations processes, then create a tailored system that brings customer information, follow-ups and reporting into one place.', features: ['Custom pipelines & dashboards', 'Lead and customer management', 'Workflow & tool integrations'] },
  { name: 'AI Automation', icon: Sparkles, color: 'magenta', description: 'Intelligent systems that take care of the repetitive, so you can focus on growth.', detail: 'We identify practical opportunities for AI in your day-to-day operations and build reliable automations with clear human oversight. Start with one valuable workflow and expand as your needs grow.', features: ['Workflow discovery & design', 'AI assistants & integrations', 'Monitoring & human handoffs'] },
  { name: 'Social Media Management', icon: MessagesSquare, color: 'cyan', description: 'Meaningful content and a consistent presence that move your brand forward.', detail: 'We bring strategy, content planning and community management together to create a social presence that feels unmistakably yours. Reporting connects the work to the goals that matter to your business.', features: ['Channel strategy & calendars', 'Content & community management', 'Performance reporting'] },
  { name: 'GMB Automation', icon: MapPin, color: 'pink', description: 'Keep your Google Business Profile active, accurate and ready to be discovered.', detail: 'We streamline your Google Business Profile updates and local presence. From consistent information to scheduled posts and review workflows, your business stays easier to find and connect with.', features: ['Profile & local visibility setup', 'Posts and update workflows', 'Review monitoring & reporting'] },
  { name: 'Shopify Store Development', icon: ShoppingBag, color: 'teal', description: 'Distinctive shopping experiences built to convert, connect and scale.', detail: 'We create Shopify stores that balance brand expression with effortless shopping. From storefront design and product setup to app integrations, we build a foundation your team can manage.', features: ['Custom storefront & theme setup', 'Catalog and checkout configuration', 'Apps, analytics & integrations'] },
];
export const projects = [
 { name: 'Social Media Growth', result: '+320% Engagement', image: 'work-portrait', category: 'Social Media Management', description: 'A cohesive editorial direction and consistent content system designed to turn a fashion brand’s audience into an engaged community.', approach: 'Audience discovery, visual direction, content calendar and performance review.' },
 { name: 'Brand Repositioning', result: '+2.6x Revenue', image: 'work-device', category: 'Website Development', description: 'A refined digital presence for a technology brand, connecting a clear product story with an intuitive customer journey.', approach: 'Positioning workshop, responsive website design and conversion-focused development.' },
 { name: 'Content Campaign', result: '10M+ Views', image: 'work-architecture', category: 'Social Media Management', description: 'A distinctive visual campaign built around architectural detail, thoughtful storytelling and a consistent brand voice.', approach: 'Campaign concept, creative production, channel planning and measurement.' },
 { name: 'SEO & Paid Ads', result: '+180% Leads', image: 'work-mobile', category: 'Website Development', description: 'A focused acquisition experience that connects customer intent with a clear offer and an effortless enquiry flow.', approach: 'Landing-page strategy, performance optimization and connected lead workflows.' },
];
export const steps = [
 { name:'Discover', text:'Understand your goals and audience.', icon:Search, detail:'We listen first. Together, we map your goals, audience, current tools and the opportunities with the most potential.' },
 { name:'Plan', text:'Create a tailored strategy.', icon:Route, detail:'We turn what we learn into a focused roadmap, with clear deliverables, milestones and measures of success.' },
 { name:'Execute', text:'Bring ideas to life across channels.', icon:Rocket, detail:'Our design and development teams bring the plan to life, with regular checkpoints and room for your feedback.' },
 { name:'Grow', text:'Measure, optimize and scale.', icon:ChartNoAxesCombined, detail:'We review results against your goals, improve what matters and build on the systems that work.' },
];
export const testimonials = [
 { quote:'Nexora transformed our online presence. The results speak for themselves!', name:'Sarah Johnson', role:'Founder, Lume', initials:'SJ', tone:'rose' },
 { quote:'Professional, creative, and incredibly effective. Highly recommended!', name:'Michael Chen', role:'CEO, Orbit', initials:'MC', tone:'blue' },
 { quote:'They don’t just deliver services, they bring real growth to your business.', name:'Emily Carter', role:'Marketing Head, Nova', initials:'EC', tone:'peach' },
];
export const faq = [
 ['What services do you offer?', 'We provide Website Development, Customize CRM, AI Automation, Social Media Management, GMB Automation and Shopify Store Development — all tailored to your goals.'],
 ['How do you work with clients?', 'We start by understanding your business, create a tailored plan, then work with you through design, development and launch. You receive clear milestones, regular updates and a dedicated point of contact.'],
 ['What industries do you work with?', 'We work with businesses across industries, from independent brands and retail to professional services and technology. Our approach starts with your audience and the needs of your business.'],
 ['How soon can we see results?', 'Timelines depend on the scope and your starting point. We agree on milestones and success measures before work begins, and review progress with you throughout the project.'],
 ['Do you offer custom plans?', 'Yes. We put together a plan around your goals, budget and existing systems. You can start with a single service or combine several into a connected growth strategy.'],
];
export const navigation = [['Home','#home'],['Services','#services'],['Work','#work'],['Process','#process'],['About','#about'],['Blog','blog']];
